### ISSUE TITLE
Hidden configuration options to be placed in menus for easy access

### ISSUE THREAD

**Issue by limyz** [limyz/DTXmaniaNX#119]
![image](https://user-images.githubusercontent.com/8562888/147620252-f4dcd753-2727-443d-a413-316b49c97061.png)
As highlighted by @approvedtx, some options are not visible in the GUI and require the user to meddle around with `config.ini` to enable certain settings.

- [ ] Discord Presence (see #41, #102)
- [ ] Pad Timing Window (see #112)
- [ ] Per-Input Judgements (see #93)
- [ ] Small Graph (similar to Gitadora)

**Comment by limyz** [comment]
Previously from #102

**Comment by limyz** [comment]
Part of #112

**Comment by jaredmorgs** [comment]
I also noticed the mention of "Stoic mode" in the config file.

```
; ストイックモード(0:OFF, 1:ON)
; Stoic mode. (0:OFF, 1:ON)
StoicMode=0
```

Is this still in the game?

**Comment by jaredmorgs** [comment]
Also noticed a velocity value as well to adjust cross-chatter between pads (I think)

```
; LC, HH, SD,...の入力切り捨て下限Velocity値(0～127)
; Minimum velocity value for LC, HH, SD, ... to accept.
LCVelocityMin=0
HHVelocityMin=20
SDVelocityMin=0
BDVelocityMin=0
HTVelocityMin=0
LTVelocityMin=0
FTVelocityMin=0
CYVelocityMin=0
RDVelocityMin=0
LPVelocityMin=0
LBDVelocityMin=0
```
